import { Suspense } from "react";
import { describe, expect, it, vi } from "vitest";
import { screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { http, HttpResponse } from "msw";
import { toast } from "sonner";
import { server } from "@/test/mocks/server";
import { MOCK_SUPABASE_URL } from "@/test/mocks/handlers";
import { renderWithQueryClient } from "@/test/test-utils";
import { mockRouter } from "@/test/setup";
import { TripDetailView } from "./trip-detail-view";

vi.spyOn(toast, "info");

describe("TripDetailView (Component with TanStack Query + MSW)", () => {
  it("fetches trip details via useSuspenseQuery and renders trip title and day count", async () => {
    renderWithQueryClient(
      <Suspense fallback={<div>Loading trip details...</div>}>
        <TripDetailView userId="user-123" tripId="mock-trip-123" />
      </Suspense>,
    );

    // Initial state suspends while TanStack Query fetches via Supabase client
    expect(screen.getByText("Loading trip details...")).toBeInTheDocument();

    // After MSW resolves the trip and wear_log queries, Suspense completes
    const title = await screen.findByRole("heading", {
      name: "Summer Vacation",
    });
    expect(title).toBeInTheDocument();
    expect(screen.getByText("5 Days")).toBeInTheDocument();

    // Verify day breakdown timeline generated by eachDateInRange and formatDayDate (DD/MM/YYYY)
    expect(screen.getByText(/Day 1 - 01\/10\/2026/i)).toBeInTheDocument();
    expect(screen.getByText(/Day 5 - 05\/10\/2026/i)).toBeInTheDocument();
  });

  it("dynamically renders custom trip data when MSW handler is overridden", async () => {
    // Override MSW to return a 2-day Kyoto trip
    server.use(
      http.get(`${MOCK_SUPABASE_URL}/rest/v1/trip`, () => {
        return HttpResponse.json({
          id: "kyoto-456",
          name: "Weekend in Kyoto",
          start_date: "2026-11-14",
          end_date: "2026-11-15",
          season: "autumn",
          travel_companion: "solo",
          user_id: "user-123",
        });
      }),
    );

    renderWithQueryClient(
      <Suspense fallback={<div>Loading trip...</div>}>
        <TripDetailView userId="user-123" tripId="kyoto-456" />
      </Suspense>,
    );

    const title = await screen.findByRole("heading", {
      name: "Weekend in Kyoto",
    });
    expect(title).toBeInTheDocument();
    expect(screen.getByText("2 Days")).toBeInTheDocument();
    expect(screen.getByText(/Day 1 - 14\/11\/2026/i)).toBeInTheDocument();
    expect(screen.getByText(/Day 2 - 15\/11\/2026/i)).toBeInTheDocument();
  });

  it("navigates back when clicking the back button", async () => {
    const user = userEvent.setup();

    renderWithQueryClient(
      <Suspense fallback={<div>Loading trip...</div>}>
        <TripDetailView userId="user-123" tripId="mock-trip-123" />
      </Suspense>,
    );

    await screen.findByRole("heading", { name: "Summer Vacation" });

    const backButton = screen.getByRole("button", { name: /go back/i });
    await user.click(backButton);

    expect(mockRouter.back).toHaveBeenCalledTimes(1);
  });
});
