import { uploadOutfitPhoto } from "@/lib/outfitStorage";
import { createBrowserSupabaseClient } from "@/lib/supabase/client";
import type { OutfitProcessingResult } from "@/stores/outfit-diary-upload-store";
import {
  layoutExtractedGarments,
  getPrimaryProcessedImageUrl,
  type StagedGarmentRow,
} from "./garmentComposition";
import type { CompositionItem } from "@/domains/outfit/components/outfit-composition";

/**
 * Dual Action Calendar Ingestion:
 * Saves the outfit photo for the calendar diary entry and simultaneously
 * triggers the background Edge Function garment extraction pipeline into
 * the wardrobe approval queue.
 */
export interface ProcessOutfitPhotoOptions {
  onStepChange?: (step: "uploading" | "extracting" | "completed") => void;
}

export async function processOutfitPhoto(
  userId: string,
  file: File,
  options?: ProcessOutfitPhotoOptions,
): Promise<OutfitProcessingResult> {
  options?.onStepChange?.("uploading");
  const uploadId = crypto.randomUUID();
  const original = await uploadOutfitPhoto(userId, uploadId, file);

  const supabase = createBrowserSupabaseClient();
  const { data: job, error: jobError } = await supabase
    .from("upload_job")
    .insert({
      user_id: userId,
      source_type: "calendar",
      original_image_url: original.url,
      status: "pending",
    })
    .select("id")
    .single();

  if (jobError) {
    console.error("Error staging wardrobe upload job from calendar:", jobError);
    throw jobError;
  }

  let compositionItems: CompositionItem[] = [];
  let primaryProcessedImageUrl = original.url;

  if (job?.id) {
    options?.onStepChange?.("extracting");
    const { error: invokeError } = await supabase.functions.invoke(
      "extract-garments",
      {
        body: {
          uploadJobId: job.id,
          imageUrl: original.url,
          userId,
        },
      },
    );

    if (invokeError) {
      console.error(
        "Garment extraction invocation failed for calendar outfit:",
        invokeError,
      );
      throw invokeError;
    }

    // Fetch the staged wardrobe items generated by the extraction pipeline
    const { data: stagedRows, error: fetchError } = await supabase
      .from("wardrobe_item")
      .select(
        "id, item:item_id (item_id, name, image_url, category, subcategory)",
      )
      .eq("upload_job_id", job.id);

    if (fetchError) {
      console.warn(
        "Failed to query staged wardrobe items for outfit diary:",
        fetchError,
      );
    } else if (stagedRows && stagedRows.length > 0) {
      const rows = stagedRows as unknown as StagedGarmentRow[];
      compositionItems = layoutExtractedGarments(rows);
      const primary = getPrimaryProcessedImageUrl(compositionItems, rows);
      if (primary) {
        primaryProcessedImageUrl = primary;
      }
    }
  }

  options?.onStepChange?.("completed");

  return {
    originalUrl: original.url,
    originalPath: original.path,
    previewUrl: primaryProcessedImageUrl,
    uploadJobId: job?.id,
    items: compositionItems.length > 0 ? compositionItems : undefined,
  };
}
